// GENERATED BY THE COMMAND ABOVE; DO NOT EDIT
// This file was generated by swaggo/swag

package docs

import (
	"bytes"
	"encoding/json"
	"strings"

	"github.com/alecthomas/template"
	"github.com/swaggo/swag"
)

var doc = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{.Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "license": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/v1_0/ai/prompts": {
            "get": {
                "tags": [
                    "AIPrompts"
                ],
                "summary": "获取所有提示词",
                "parameters": [
                    {
                        "type": "string",
                        "description": "token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/ai_m.AiPromptData"
                            }
                        }
                    }
                }
            }
        },
        "/v1_0/album/add": {
            "post": {
                "tags": [
                    "相册"
                ],
                "summary": "添加",
                "parameters": [
                    {
                        "type": "string",
                        "description": "token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "integer"
                        }
                    }
                }
            }
        },
        "/v1_0/album/del/:id": {
            "delete": {
                "tags": [
                    "相册"
                ],
                "summary": "删除",
                "parameters": [
                    {
                        "type": "string",
                        "description": "token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "integer"
                        }
                    }
                }
            }
        },
        "/v1_0/album/detail": {
            "post": {
                "tags": [
                    "相册"
                ],
                "summary": "明细",
                "parameters": [
                    {
                        "type": "string",
                        "description": "token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Album id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "请求体",
                        "name": "ProcessReq",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/album_r.ProcessReq"
                        }
                    }
                ],
                "responses": {
                    "200": {}
                }
            }
        },
        "/v1_0/album/detail/:id": {
            "get": {
                "tags": [
                    "相册"
                ],
                "summary": "明细",
                "parameters": [
                    {
                        "type": "string",
                        "description": "token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Album id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/v1_0/album/list": {
            "get": {
                "tags": [
                    "相册"
                ],
                "summary": "列表",
                "parameters": [
                    {
                        "type": "string",
                        "description": "token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "type": "integer"
                            }
                        }
                    }
                }
            }
        },
        "/v1_0/authorizations": {
            "post": {
                "tags": [
                    "用户"
                ],
                "summary": "登录",
                "parameters": [
                    {
                        "description": "请求体",
                        "name": "UserAuthReq",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/user_r.UserAuthReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/user_r.UserAuthResp"
                        }
                    }
                }
            }
        },
        "/v1_0/channels": {
            "get": {
                "tags": [
                    "频道"
                ],
                "summary": "列表",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/channel_r.ChannelsResp"
                        }
                    }
                }
            }
        },
        "/v1_0/chatgpt/process": {
            "post": {
                "tags": [
                    "Chatgpt"
                ],
                "summary": "请求",
                "parameters": [
                    {
                        "type": "string",
                        "description": "token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "请求体",
                        "name": "ProcessReq",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/chatgpt_r.ProcessReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/chatgpt_r.ProcessReq"
                        }
                    }
                }
            }
        },
        "/v1_0/chatgpt/session/add": {
            "post": {
                "tags": [
                    "Chatgpt"
                ],
                "summary": "添加一个会话",
                "parameters": [
                    {
                        "type": "string",
                        "description": "token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "integer"
                        }
                    }
                }
            }
        },
        "/v1_0/chatgpt/session/del/:id": {
            "delete": {
                "tags": [
                    "Chatgpt"
                ],
                "summary": "删除一个会话",
                "parameters": [
                    {
                        "type": "string",
                        "description": "token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "integer"
                        }
                    }
                }
            }
        },
        "/v1_0/chatgpt/session/detail/:id": {
            "get": {
                "tags": [
                    "Chatgpt"
                ],
                "summary": "会话明细",
                "parameters": [
                    {
                        "type": "string",
                        "description": "token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "session id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/chatgpt_r.ProcessReq"
                        }
                    }
                }
            }
        },
        "/v1_0/chatgpt/session/list": {
            "get": {
                "tags": [
                    "Chatgpt"
                ],
                "summary": "会话列表",
                "parameters": [
                    {
                        "type": "string",
                        "description": "token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "type": "integer"
                            }
                        }
                    }
                }
            }
        },
        "/v1_0/mp/articles": {
            "get": {
                "tags": [
                    "文章"
                ],
                "summary": "详情",
                "parameters": [
                    {
                        "type": "string",
                        "description": "请求体",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "页码",
                        "name": "page",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "页数",
                        "name": "per_page",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "频道名称",
                        "name": "channel_id",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "发布开始日期:2006-01-02",
                        "name": "begin_pubdate",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "发布结束日期:2006-01-02",
                        "name": "end_pubdate",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/article_r.ListArticleResp"
                        }
                    }
                }
            },
            "post": {
                "tags": [
                    "文章"
                ],
                "summary": "发布",
                "parameters": [
                    {
                        "type": "string",
                        "description": "请求体",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "是否草稿",
                        "name": "draft",
                        "in": "query"
                    },
                    {
                        "description": "请求体",
                        "name": "PostArticleReq",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/article_r.PostArticleReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/article_r.PostPutArticleResp"
                        }
                    }
                }
            }
        },
        "/v1_0/mp/articles/:id": {
            "get": {
                "tags": [
                    "文章"
                ],
                "summary": "详情",
                "parameters": [
                    {
                        "type": "string",
                        "description": "请求体",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "文章id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/article_r.GetArticleResp"
                        }
                    }
                }
            },
            "put": {
                "tags": [
                    "文章"
                ],
                "summary": "修改",
                "parameters": [
                    {
                        "type": "string",
                        "description": "请求体",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "是否草稿",
                        "name": "draft",
                        "in": "query"
                    },
                    {
                        "description": "请求体",
                        "name": "PutArticleReq",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/article_r.PutArticleReq"
                        }
                    },
                    {
                        "type": "string",
                        "description": "修改id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/article_r.PostPutArticleResp"
                        }
                    }
                }
            },
            "delete": {
                "tags": [
                    "文章"
                ],
                "summary": "删除",
                "parameters": [
                    {
                        "type": "string",
                        "description": "请求体",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "文章id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {}
                }
            }
        },
        "/v1_0/mp/todolist": {
            "get": {
                "tags": [
                    "Todo模块"
                ],
                "summary": "列表",
                "parameters": [
                    {
                        "type": "string",
                        "description": "token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/todo_r.CvTodoList"
                            }
                        }
                    }
                }
            },
            "post": {
                "tags": [
                    "Todo模块"
                ],
                "summary": "添加",
                "parameters": [
                    {
                        "type": "string",
                        "description": "token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "请求体",
                        "name": "AddTodoListReq",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/todo_r.AddTodoListReq"
                        }
                    }
                ],
                "responses": {
                    "200": {}
                }
            }
        },
        "/v1_0/mp/todolist/:id": {
            "put": {
                "tags": [
                    "Todo模块"
                ],
                "summary": "标记",
                "parameters": [
                    {
                        "type": "string",
                        "description": "token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "请求体",
                        "name": "MarkTodoListReq",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/todo_r.MarkTodoListReq"
                        }
                    }
                ],
                "responses": {
                    "200": {}
                }
            },
            "delete": {
                "tags": [
                    "Todo模块"
                ],
                "summary": "删除",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {}
                }
            }
        },
        "/v1_0/mp/todolist/markAll": {
            "post": {
                "tags": [
                    "Todo模块"
                ],
                "summary": "标记全部",
                "parameters": [
                    {
                        "type": "string",
                        "description": "token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "请求体",
                        "name": "MarkAllTodoListReq",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/todo_r.MarkAllTodoListReq"
                        }
                    }
                ],
                "responses": {
                    "200": {}
                }
            }
        },
        "/v1_0/music/author/down": {
            "post": {
                "tags": [
                    "音乐"
                ],
                "summary": "下载歌手歌单",
                "parameters": [
                    {
                        "type": "string",
                        "description": "token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "歌单id",
                        "name": "MusicAuthorDownReq",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/music_r.MusicAuthorDownReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/music_r.Music"
                            }
                        }
                    }
                }
            }
        },
        "/v1_0/music/author/list": {
            "get": {
                "tags": [
                    "音乐"
                ],
                "summary": "歌单列表",
                "parameters": [
                    {
                        "type": "string",
                        "description": "token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/music_r.Playlist"
                            }
                        }
                    }
                }
            }
        },
        "/v1_0/music/author/search": {
            "get": {
                "tags": [
                    "音乐"
                ],
                "summary": "搜索歌手歌单",
                "parameters": [
                    {
                        "type": "string",
                        "description": "token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "搜索内容",
                        "name": "q",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/music_r.Playlist"
                            }
                        }
                    }
                }
            }
        },
        "/v1_0/music/down": {
            "get": {
                "tags": [
                    "音乐"
                ],
                "summary": "搜索",
                "parameters": [
                    {
                        "type": "string",
                        "description": "token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "歌id",
                        "name": "id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/music_r.Music"
                        }
                    }
                }
            }
        },
        "/v1_0/music/list": {
            "get": {
                "tags": [
                    "音乐"
                ],
                "summary": "列表",
                "parameters": [
                    {
                        "type": "string",
                        "description": "token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "歌单id",
                        "name": "playlistId",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/music_r.Music"
                            }
                        }
                    }
                }
            }
        },
        "/v1_0/music/search": {
            "get": {
                "tags": [
                    "音乐"
                ],
                "summary": "搜索",
                "parameters": [
                    {
                        "type": "string",
                        "description": "token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "搜索词",
                        "name": "q",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/music_r.Music"
                            }
                        }
                    }
                }
            }
        },
        "/v1_0/music/{id}": {
            "delete": {
                "tags": [
                    "音乐"
                ],
                "summary": "删除",
                "parameters": [
                    {
                        "type": "string",
                        "description": "token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "歌id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/music_r.Music"
                        }
                    }
                }
            }
        },
        "/v1_0/user/profile": {
            "get": {
                "tags": [
                    "用户"
                ],
                "summary": "资料",
                "parameters": [
                    {
                        "type": "string",
                        "description": "请求体",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/user_r.UserProfileResp"
                        }
                    }
                }
            },
            "put": {
                "tags": [
                    "用户"
                ],
                "summary": "更新资料",
                "parameters": [
                    {
                        "type": "string",
                        "description": "请求体",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "请求体",
                        "name": "PutUserProfileReq",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/user_r.PutUserProfileReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/user_r.UserProfileResp"
                        }
                    }
                }
            }
        },
        "/v1_0/vap/vapc": {
            "post": {
                "tags": [
                    "VAP"
                ],
                "summary": "获取vapc",
                "parameters": [
                    {
                        "type": "string",
                        "description": "token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "mp4",
                        "name": "mp4",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {}
                }
            }
        }
    },
    "definitions": {
        "ai_m.AiPromptData": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string"
                },
                "name": {
                    "type": "object",
                    "properties": {
                        "en": {
                            "type": "string"
                        },
                        "zh": {
                            "type": "string"
                        }
                    }
                },
                "subTabs": {
                    "type": "array",
                    "items": {
                        "type": "object",
                        "properties": {
                            "code": {
                                "type": "string"
                            },
                            "name": {
                                "type": "object",
                                "properties": {
                                    "en": {
                                        "type": "string"
                                    },
                                    "zh": {
                                        "type": "string"
                                    }
                                }
                            },
                            "prompts": {
                                "type": "array",
                                "items": {
                                    "type": "object",
                                    "properties": {
                                        "code": {
                                            "type": "string"
                                        },
                                        "en": {
                                            "type": "string"
                                        },
                                        "zh": {
                                            "type": "string"
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }
        },
        "album_r.ProcessReq": {
            "type": "object",
            "properties": {
                "albumId": {
                    "type": "integer"
                },
                "images": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "article_r.ArticleCover": {
            "type": "object",
            "properties": {
                "images": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "type": {
                    "type": "integer"
                }
            }
        },
        "article_r.GetArticleResp": {
            "type": "object",
            "properties": {
                "channel_id": {
                    "type": "integer"
                },
                "content": {
                    "type": "string"
                },
                "cover": {
                    "type": "object",
                    "$ref": "#/definitions/article_r.ArticleCover"
                },
                "id": {
                    "type": "string"
                },
                "pub_date": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                }
            }
        },
        "article_r.ListArticle": {
            "type": "object",
            "properties": {
                "comment_count": {
                    "type": "integer"
                },
                "cover": {
                    "type": "object",
                    "$ref": "#/definitions/article_r.ArticleCover"
                },
                "id": {
                    "type": "string"
                },
                "like_count": {
                    "type": "integer"
                },
                "pubdate": {
                    "type": "string"
                },
                "read_count": {
                    "type": "integer"
                },
                "status": {
                    "type": "integer"
                },
                "title": {
                    "type": "string"
                }
            }
        },
        "article_r.ListArticleResp": {
            "type": "object",
            "properties": {
                "page": {
                    "type": "integer"
                },
                "per_page": {
                    "type": "integer"
                },
                "results": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/article_r.ListArticle"
                    }
                },
                "total_count": {
                    "type": "integer"
                }
            }
        },
        "article_r.PostArticleReq": {
            "type": "object",
            "required": [
                "channel_id",
                "content",
                "title",
                "type"
            ],
            "properties": {
                "channel_id": {
                    "type": "string"
                },
                "content": {
                    "type": "string"
                },
                "cover": {
                    "type": "object",
                    "$ref": "#/definitions/article_r.ArticleCover"
                },
                "title": {
                    "type": "string"
                },
                "type": {
                    "type": "integer"
                }
            }
        },
        "article_r.PostPutArticleResp": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string"
                }
            }
        },
        "article_r.PutArticleReq": {
            "type": "object",
            "required": [
                "channel_id",
                "content",
                "title",
                "type"
            ],
            "properties": {
                "channel_id": {
                    "type": "integer"
                },
                "content": {
                    "type": "string"
                },
                "cover": {
                    "type": "object",
                    "$ref": "#/definitions/article_r.ArticleCover"
                },
                "title": {
                    "type": "string"
                },
                "type": {
                    "type": "integer"
                }
            }
        },
        "channel_r.ChannelData": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "channel_r.ChannelsResp": {
            "type": "object",
            "properties": {
                "channels": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/channel_r.ChannelData"
                    }
                }
            }
        },
        "chatgpt_r.ProcessContent": {
            "type": "object",
            "properties": {
                "content": {
                    "type": "string"
                },
                "createdTime": {
                    "type": "string"
                },
                "role": {
                    "description": "user | assistant",
                    "type": "string"
                }
            }
        },
        "chatgpt_r.ProcessReq": {
            "type": "object",
            "properties": {
                "messages": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/chatgpt_r.ProcessContent"
                    }
                },
                "session_id": {
                    "type": "integer"
                }
            }
        },
        "music_r.Music": {
            "type": "object",
            "properties": {
                "artist": {
                    "description": "歌手",
                    "type": "string"
                },
                "cover": {
                    "description": "音乐封面",
                    "type": "string"
                },
                "duration": {
                    "description": "格式化歌曲时长",
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "lyric": {
                    "description": "歌词",
                    "type": "string"
                },
                "name": {
                    "description": "歌曲名",
                    "type": "string"
                },
                "url": {
                    "description": "音乐mp3",
                    "type": "string"
                }
            }
        },
        "music_r.MusicAuthorDownReq": {
            "type": "object",
            "properties": {
                "desc": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "pic": {
                    "type": "string"
                }
            }
        },
        "music_r.Playlist": {
            "type": "object",
            "properties": {
                "desc": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "pic": {
                    "type": "string"
                }
            }
        },
        "todo_r.AddTodoListReq": {
            "type": "object",
            "required": [
                "name"
            ],
            "properties": {
                "name": {
                    "type": "string"
                }
            }
        },
        "todo_r.CvTodoList": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer"
                },
                "isDone": {
                    "type": "boolean"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "todo_r.MarkAllTodoListReq": {
            "type": "object",
            "properties": {
                "isDone": {
                    "type": "boolean"
                }
            }
        },
        "todo_r.MarkTodoListReq": {
            "type": "object",
            "properties": {
                "isDone": {
                    "type": "boolean"
                }
            }
        },
        "user_r.PutUserProfileReq": {
            "type": "object",
            "properties": {
                "gender": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "user_r.UserAuthReq": {
            "type": "object",
            "required": [
                "code",
                "mobile"
            ],
            "properties": {
                "code": {
                    "description": "验证码",
                    "type": "string"
                },
                "mobile": {
                    "description": "手机号",
                    "type": "string"
                }
            }
        },
        "user_r.UserAuthResp": {
            "type": "object",
            "properties": {
                "refresh_token": {
                    "description": "token",
                    "type": "string"
                },
                "token": {
                    "description": "token",
                    "type": "string"
                }
            }
        },
        "user_r.UserProfileResp": {
            "type": "object",
            "properties": {
                "birthday": {
                    "type": "string"
                },
                "gender": {
                    "type": "integer"
                },
                "id": {
                    "type": "string"
                },
                "mobile": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "photo": {
                    "type": "string"
                }
            }
        }
    }
}`

type swaggerInfo struct {
	Version     string
	Host        string
	BasePath    string
	Schemes     []string
	Title       string
	Description string
}

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = swaggerInfo{
	Version:     "",
	Host:        "",
	BasePath:    "",
	Schemes:     []string{},
	Title:       "",
	Description: "",
}

type s struct{}

func (s *s) ReadDoc() string {
	sInfo := SwaggerInfo
	sInfo.Description = strings.Replace(sInfo.Description, "\n", "\\n", -1)

	t, err := template.New("swagger_info").Funcs(template.FuncMap{
		"marshal": func(v interface{}) string {
			a, _ := json.Marshal(v)
			return string(a)
		},
	}).Parse(doc)
	if err != nil {
		return doc
	}

	var tpl bytes.Buffer
	if err := t.Execute(&tpl, sInfo); err != nil {
		return doc
	}

	return tpl.String()
}

func init() {
	swag.Register(swag.Name, &s{})
}
